// examples/framework-integration/svelte-threlte/src/lib/components/RotatingBox.svelte
<script lang="ts">
  import { T, useTask } from '@threlte/core';
  import * as THREE from 'three';
  
  export let position: [number, number, number] = [0, 0, 0];
  
  let mesh: THREE.Mesh;
  let hovered = false;
  let clicked = false;
  
  // Animation loop
  useTask((delta) => {
    if (mesh) {
      mesh.rotation.x += delta * 0.5;
      mesh.rotation.y += delta * 0.3;
    }
  });
</script>

<T.Mesh
  bind:ref={mesh}
  {position}
  scale={clicked ? 1.2 : 1}
  castShadow
  on:click={() => clicked = !clicked}
  on:pointerenter={() => hovered = true}
  on:pointerleave={() => hovered = false}
>
  <T.BoxGeometry args={[1.5, 1.5, 1.5]} />
  <T.MeshStandardMaterial
    color={hovered ? '#ff6b6b' : '#4ecdc4'}
    roughness={0.3}
    metalness={0.5}
  />
</T.Mesh>

// examples/framework-integration/nextjs-ssr/src/components/RotatingBox.tsx
'use client';

import { useRef, useState } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

interface RotatingBoxProps {
  position?: [number, number, number];
}

export function RotatingBox({ position = [0, 0, 0] }: RotatingBoxProps) {
  const meshRef = useRef<THREE.Mesh>(null!);
  const [hovered, setHovered] = useState(false);
  const [clicked, setClicked] = useState(false);

  useFrame((_, delta) => {
    if (meshRef.current) {
      meshRef.current.rotation.x += delta * 0.5;
      meshRef.current.rotation.y += delta * 0.3;
    }
  });

  return (
    <mesh
      ref={meshRef}
      position={position}
      scale={clicked ? 1.2 : 1}
      onClick={() => setClicked(!clicked)}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <boxGeometry args={[1.5, 1.5, 1.5]} />
      <meshStandardMaterial
        color={hovered ? '#ff6b6b' : '#4ecdc4'}
        roughness={0.3}
        metalness={0.5}
      />
    </mesh>
  );
}
