// examples/framework-integration/svelte-threlte/src/lib/components/TorusGroup.svelte
<script lang="ts">
  import { T, useTask } from '@threlte/core';
  import * as THREE from 'three';
  
  export let position: [number, number, number] = [0, 0, 0];
  
  let group: THREE.Group;
  let torus1: THREE.Mesh;
  let torus2: THREE.Mesh;
  let torus3: THREE.Mesh;
  let elapsed = 0;
  
  const torusArgs: [number, number, number, number] = [0.5, 0.15, 16, 32];
  
  // Animation loop
  useTask((delta) => {
    elapsed += delta;
    
    if (group) {
      group.rotation.y = elapsed * 0.3;
    }
    
    if (torus1) torus1.rotation.x = elapsed * 2;
    if (torus2) torus2.rotation.x = elapsed * 2 + Math.PI * 0.66;
    if (torus3) torus3.rotation.x = elapsed * 2 + Math.PI * 1.33;
  });
</script>

<T.Group bind:ref={group} {position}>
  <!-- Red torus -->
  <T.Mesh bind:ref={torus1} position={[1.5, 0, 0]} castShadow>
    <T.TorusGeometry args={torusArgs} />
    <T.MeshStandardMaterial color="#e74c3c" roughness={0.4} />
  </T.Mesh>
  
  <!-- Green torus -->
  <T.Mesh bind:ref={torus2} position={[-0.75, 1.3, 0]} castShadow>
    <T.TorusGeometry args={torusArgs} />
    <T.MeshStandardMaterial color="#2ecc71" roughness={0.4} />
  </T.Mesh>
  
  <!-- Blue torus -->
  <T.Mesh bind:ref={torus3} position={[-0.75, -1.3, 0]} castShadow>
    <T.TorusGeometry args={torusArgs} />
    <T.MeshStandardMaterial color="#3498db" roughness={0.4} />
  </T.Mesh>
</T.Group>

// examples/framework-integration/nextjs-ssr/src/components/TorusGroup.tsx
'use client';

import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

interface TorusGroupProps {
  position?: [number, number, number];
}

export function TorusGroup({ position = [0, 0, 0] }: TorusGroupProps) {
  const groupRef = useRef<THREE.Group>(null!);
  const torus1Ref = useRef<THREE.Mesh>(null!);
  const torus2Ref = useRef<THREE.Mesh>(null!);
  const torus3Ref = useRef<THREE.Mesh>(null!);

  useFrame((state) => {
    const t = state.clock.elapsedTime;

    if (groupRef.current) {
      groupRef.current.rotation.y = t * 0.3;
    }

    if (torus1Ref.current) torus1Ref.current.rotation.x = t * 2;
    if (torus2Ref.current) torus2Ref.current.rotation.x = t * 2 + Math.PI * 0.66;
    if (torus3Ref.current) torus3Ref.current.rotation.x = t * 2 + Math.PI * 1.33;
  });

  const torusArgs: [number, number, number, number] = [0.5, 0.15, 16, 32];

  return (
    <group ref={groupRef} position={position}>
      <mesh ref={torus1Ref} position={[1.5, 0, 0]} castShadow>
        <torusGeometry args={torusArgs} />
        <meshStandardMaterial color="#e74c3c" roughness={0.4} />
      </mesh>

      <mesh ref={torus2Ref} position={[-0.75, 1.3, 0]} castShadow>
        <torusGeometry args={torusArgs} />
        <meshStandardMaterial color="#2ecc71" roughness={0.4} />
      </mesh>

      <mesh ref={torus3Ref} position={[-0.75, -1.3, 0]} castShadow>
        <torusGeometry args={torusArgs} />
        <meshStandardMaterial color="#3498db" roughness={0.4} />
      </mesh>
    </group>
  );
}
