// examples/framework-integration/react-three-fiber/src/components/Scene.tsx
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { OrbitControls, Environment, ContactShadows } from '@react-three/drei';
import * as THREE from 'three';

import { RotatingBox } from './RotatingBox';
import { AnimatedSphere } from './AnimatedSphere';
import { Ground } from './Ground';
import { Lights } from './Lights';
import { TorusGroup } from './TorusGroup';

/**
 * Main Scene Component
 * 
 * Contains all 3D objects and demonstrates various Three.js features
 * that 3Lens can inspect and monitor.
 */
export function Scene() {
  return (
    <>
      {/* Lighting */}
      <Lights />
      
      {/* Environment for reflections */}
      <Environment preset="city" />
      
      {/* Ground plane with contact shadows */}
      <Ground />
      <ContactShadows
        position={[0, -0.49, 0]}
        opacity={0.4}
        scale={10}
        blur={2}
        far={4}
      />
      
      {/* Animated objects */}
      <RotatingBox position={[-2, 1, 0]} />
      <AnimatedSphere position={[2, 1, 0]} />
      <TorusGroup position={[0, 2, -2]} />
      
      {/* Camera controls */}
      <OrbitControls 
        makeDefault
        enableDamping
        dampingFactor={0.05}
        minDistance={3}
        maxDistance={20}
      />
    </>
  );
}

// examples/framework-integration/svelte-threlte/src/lib/components/Scene.svelte
<script lang="ts">
  import { T } from '@threlte/core';
  import { OrbitControls, ContactShadows } from '@threlte/extras';
  import RotatingBox from './RotatingBox.svelte';
  import AnimatedSphere from './AnimatedSphere.svelte';
  import TorusGroup from './TorusGroup.svelte';
  import Ground from './Ground.svelte';
  import Lights from './Lights.svelte';
</script>

<!-- Camera -->
<T.PerspectiveCamera
  makeDefault
  position={[5, 5, 8]}
  fov={60}
/>

<!-- Lighting -->
<Lights />

<!-- Scene background -->
<T.Color attach="background" args={['#0a0a0f']} />
<T.Fog attach="fog" args={['#0a0a0f', 10, 50]} />

<!-- Ground plane with contact shadows -->
<Ground />
<ContactShadows
  position={[0, -0.49, 0]}
  opacity={0.4}
  scale={10}
  blur={2}
  far={4}
/>

<!-- Animated objects -->
<RotatingBox position={[-2, 1, 0]} />
<AnimatedSphere position={[2, 1, 0]} />
<TorusGroup position={[0, 2, -2]} />

<!-- Camera controls -->
<OrbitControls
  enableDamping
  dampingFactor={0.05}
  minDistance={3}
  maxDistance={20}
/>
